spring.application.name=knowhub

spring.datasource.url=jdbc:sqlserver://localhost:1434;databaseName=knowhub;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=ChuDucHai@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

# cloudinary
cloudinary.cloud-name=de9q53xt1
cloudinary.api-key=177862363221212
cloudinary.api-secret=qZRL3njKTYw2LkU0mZqBrHO89vE

# media
media.max-file-size=104857600
# enable multipart
spring.servlet.multipart.enabled=true
# gioi han file
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=200MB
